# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Textos sobre acessibilidade na web em português
#email: your-email@domain.com
description: >
  Aqui você encontra textos traduzidos sobre acessibilidade na web no idioma português. Seu foco é permitir que colaboradores indiquem textos pertinentes sobre o tema e, depois de discussão, seja traduzido por outros colaboradores.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acessibilidade.pt.webiwg.org" # the base hostname & protocol for your site
twitter_username: WebIWG
github_username:  Dkmister/acessibilidade-web-pt

# Build settings
markdown: kramdown
theme: minima
